In [1]:
import numpy as np

# array definations

In [3]:
ll=[1,2,3,4,5] # regular list
a=np.array([1,2,3,4]) # numpy array
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[1,2,3],[4,5,6]],dtype=np.int16)

print(ll)
print(a)

[1, 2, 3, 4, 5]
[1 2 3 4]


# basic operations

In [5]:
print(type(a)) #which type the array is
print(a.size) #attribute size gives total size
print(a.shape)#shape(row,column)

print(b.shape)

<class 'numpy.ndarray'>
4
(4,)
(2, 3)


In [6]:
print(a.dtype)
print(b.dtype)

int32
int32


In [7]:
print(c)
print("After")
print(c.transpose())

[[1 2 3]
 [4 5 6]]
After
[[1 4]
 [2 5]
 [3 6]]


# common ways to create arrays

In [9]:
arr=np.empty((3,3)) #by default np arrays with empty ones and zeros is float. we can specify dtype
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr2=np.ones(5,dtype=int) #create array with only 1 in the array
arr2

array([1, 1, 1, 1, 1])

In [11]:
x=np.arange(20) #create an array from 1 to before the limit like range value
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
x1=np.arange(5,20,5) # start,end,step
x1

array([ 5, 10, 15])

# array manipulation

In [14]:
x.reshape((4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
x # reshape just creates a clone of an array with changed dimension, doesnt affect main array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
x=x.reshape((4,5))
x=x.flatten() # reverse process of reshape

In [17]:
x[15] # 15th element in the array

15

In [18]:
x[8:] #from 8 index to end

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
x[7:9] #from 7 index to before 9 index

array([7, 8])

# mathematical operations

In [21]:
array1=np.arange(20).reshape(4,5)
array2=np.arange(20,40).reshape(4,5)

In [22]:
print(array1)
print(array2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]


In [23]:
array1+array2 # adds two arrrays

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [24]:
array1-array2

array([[-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20]])

In [25]:
np.multiply(array1,array2) #this is dot multiplications. means just multiply index values and create new array

array([[  0,  21,  44,  69,  96],
       [125, 156, 189, 224, 261],
       [300, 341, 384, 429, 476],
       [525, 576, 629, 684, 741]])

In [26]:
a=np.arange(1,7).reshape(2,3)
b=np.arange(7,13).reshape(3,2)
print(a)
print(b)
print("\n")
print(a@b) # matrix multiplication actual way

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


[[ 58  64]
 [139 154]]


In [27]:
import numpy as np

# Define two 2D arrays where each row is a vector
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Compute the cross product for each pair of vectors
cross_product = np.cross(a, b)

print("Cross product:\n", cross_product)


Cross product:
 [[-6 12 -6]
 [-6 12 -6]]


In [28]:
array1.min()

0

In [29]:
array1.max()

19

In [30]:
np.sum(array1)

190

In [31]:
np.sum(array1,1)

array([10, 35, 60, 85])

In [73]:
np.sum(arr[1,:]) #sum every value of index 1 in the array

15

# working with random values in numpy

In [33]:
arr=np.random.random(5)
arr

array([0.16292432, 0.20553647, 0.14389939, 0.89144771, 0.32825885])

In [34]:
arr=np.random.randint(3,11,size=(4,4))
arr

array([[ 9,  5,  6, 10],
       [ 3, 10,  4,  9],
       [ 9,  4,  3,  6],
       [ 4, 10,  5,  6]])

In [35]:
x=np.random.random(5)
print(x)
print(np.random.choice(x))

[0.66897485 0.02408981 0.12837864 0.65967033 0.41055148]
0.024089808403249258


In [36]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

15